# Generated by Django 4.2.9 on 2024-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
