# Generated by Django 4.2.9 on 2024-01-28 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
