# Generated by Django 4.2.9 on 2024-01-29 17:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_report_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
