# Generated by Django 4.2.9 on 2024-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='Report_Title', max_length=200, unique=True),
        ),
    ]
