# Generated by Django 4.2.9 on 2024-01-31 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_report_approved_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Featured Image'),
        ),
    ]
