# Generated by Django 4.2.9 on 2024-01-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_image_related_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
