# Generated by Django 4.2.9 on 2024-02-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
