# Generated by Django 4.2.9 on 2024-02-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
    ]
