# Generated by Django 4.2.9 on 2024-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_rename_excerpt_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
