# Generated by Django 4.2.9 on 2024-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('1', 'True Story'), ('2', 'Urban Legend'), ('3', 'Creative Writing'), ('4', 'Creepypasta')], default='3', max_length=250),
        ),
        migrations.AddField(
            model_name='report',
            name='image_credit',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='report',
            name='image_source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
